language: node_js
dist: trusty
sudo: required

# Test envs will overwrite defaults
env:
  - DAPPNODE=rocks

node_js:
  - "node"

cache:
  directories:
    - build/src/node_modules
    - node_modules

before_install:
  - cd build/src

install:
  # This is a dockerized application, the node app is in build/src
  - npm install

before_script:
  # Throw an error if code is not linted properly
  - npm run lint

script:
  - echo "Running mock tests"

after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coverage
  - cd ../.. # On the before_install: it cd build/src
  - ./push.sh

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      before_deploy:
        # Configure git to push latter in case of release
        - git config --global user.email "eduadiez@gmail.com"
        - git config --global user.name "eduadiez"
        - git remote rm origin
        - git remote add origin https://user:${GITHUB_TOKEN}@github.com/dappnode/DNP_VPN.git
        - travis_retry npm install -g @dappnode/dappnodesdk
        - . sdkMock.sh # just exports $VERSION_TAG
        - echo "before_deploy; CALLING ECHO ON VAR, $VERSION_TAG"
        # - git tag "v.0.0.test"
      # Advanced: optionally overwrite your default `script` step to skip the tests
      deploy:
        provider: script
        api_key: ${GITHUB_API_KEY}
        file_glob: true
        file: build_latest/*
        github-token: $GITHUB_TOKEN
        script:
          - echo "script; CALLING ECHO ON VAR, $VERSION_TAG"
          - IPFS_PROVIDER=ipfs.infura.io IPFS_PROTO=https SILENT=true PROVIDER=wss://mainnet.infura.io/ws dappnodesdk publish patch
          - npx semantic-release
        skip_cleanup: true
        on:
          branch: master
          # condition: "$CC = gcc"
      after_deploy:
        - ./push.sh
