version: '3.4'
networks:
    network:
        driver: bridge
        ipam:
            config:
                -
                    subnet: 172.33.0.0/16
volumes:
    vpndnpdappnodeeth_data: {}
services:
    vpn.dnp.dappnode.eth:
        build: ./build
        image: 'vpn.dnp.dappnode.eth:0.1.21'
        container_name: DAppNodeCore-vpn.dnp.dappnode.eth
        privileged: true
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/hostname:/etc/vpnname:ro'
            - '/usr/src/dappnode/config:/usr/src/app/config:ro'
            - '/lib/modules:/lib/modules:ro'
            - 'vpndnpdappnodeeth_data:/usr/src/app/secrets'
        ports:
            - '4500:4500/udp'
            - '500:500/udp'
        dns: 172.33.1.2
        networks:
            network:
                ipv4_address: 172.33.1.4
        logging:
            options:
                max-size: "10m"
                max-file: "3"
