version: "3.4"
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
volumes:
  vpndnpdappnodeeth_data: {}
  vpndnpdappnodeeth_config: {}
services:
  vpn.dnp.dappnode.eth:
    build: .
    image: "vpn.dnp.dappnode.eth:0.2.9"
    container_name: DAppNodeCore-vpn.dnp.dappnode.eth
    privileged: true
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/hostname:/etc/vpnname:ro"
      - "/usr/src/dappnode/config:/usr/src/app/config:ro"
      - "/lib/modules:/lib/modules:ro"
      - "vpndnpdappnodeeth_data:/usr/src/app/secrets"
      - "vpndnpdappnodeeth_config:/etc/openvpn"
    ports:
      - "1194:1194/udp"
      - "8092:8092"
    dns: 172.33.1.2
    networks:
      network:
        ipv4_address: 172.33.1.4
    logging:
      driver: journald
